# DataSource Config
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 部署到线上要 把ip地址 改成 远程服务器的ip ，用localhost不行
    url: jdbc:mysql://120.24.200.62:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: vueblog
    # mysql 密码的加密规则 必须是 mysql_native_password
    password: wyzxgzsLZH1
  redis:
    # 部署到线上要 把ip地址 改成 远程服务器的ip ，用localhost不行
      host: 120.24.200.62
      timeout: 5000
      port: 6379
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-wait: -1
          max-active: 8
      password: wyzxgzsLZH1
  mail:
      host:  smtp.163.com
      username: xzxxuenai@163.com
      password: MAOMZOBVBNHRVQBM
      default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#超级管理员角色
role:
  root-name: role_root

fanli:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    #安全密钥
    secret: a43bd0b5372e21acbb6aa8dedbd38664
    #过期时间
    expire: 172800
    # 头部
    header: jwt
