# DataSource Config
server:
  port: 8183
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: vueblog
    password: wyzxgzsLZH1
  redis:
      host: localhost
      timeout: 5000
      port: 6379
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-wait: -1
          max-active: 8
  mail:
      host:  smtp.163.com
      username: skymomail@163.com
      password: your
      default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

#超级管理员角色
role:
  root-name: role_root

fanli:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    #安全密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #过期时间
    expire: 172800
    # 头部
    header: token
